import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/ui/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        figma: {
          bg: "var(--figma-color-bg)",
          "bg-secondary": "var(--figma-color-bg-secondary)",
          "bg-tertiary": "var(--figma-color-bg-tertiary)",
          "bg-hover": "var(--figma-color-bg-hover)",
          "bg-selected": "var(--figma-color-bg-selected)",
          text: "var(--figma-color-text)",
          "text-secondary": "var(--figma-color-text-secondary)",
          "text-tertiary": "var(--figma-color-text-tertiary)",
          "text-disabled": "var(--figma-color-text-disabled)",
          border: "var(--figma-color-border)",
          "border-strong": "var(--figma-color-border-strong)",
          icon: "var(--figma-color-icon)",
          "icon-secondary": "var(--figma-color-icon-secondary)",
          "icon-tertiary": "var(--figma-color-icon-tertiary)",
        },
        neutral: {
          50: "var(--bl-neutral-50)",
          100: "var(--bl-neutral-100)",
          200: "var(--bl-neutral-200)",
          300: "var(--bl-neutral-300)",
          400: "var(--bl-neutral-400)",
          500: "var(--bl-neutral-500)",
          600: "var(--bl-neutral-600)",
          700: "var(--bl-neutral-700)",
          800: "var(--bl-neutral-800)",
          900: "var(--bl-neutral-900)",
          950: "var(--bl-neutral-950)",
        },
        violet: {
          50: "var(--bl-violet-50)",
          100: "var(--bl-violet-100)",
          200: "var(--bl-violet-200)",
          300: "var(--bl-violet-300)",
          400: "var(--bl-violet-400)",
          500: "var(--bl-violet-500)",
          600: "var(--bl-violet-600)",
          700: "var(--bl-violet-700)",
          800: "var(--bl-violet-800)",
          900: "var(--bl-violet-900)",
          950: "var(--bl-violet-950)",
        },
        success: {
          50: "var(--bl-success-50)",
          100: "var(--bl-success-100)",
          200: "var(--bl-success-200)",
          300: "var(--bl-success-300)",
          400: "var(--bl-success-400)",
          500: "var(--bl-success-500)",
          600: "var(--bl-success-600)",
          700: "var(--bl-success-700)",
          800: "var(--bl-success-800)",
          900: "var(--bl-success-900)",
        },
        sem: {
          canvas: "var(--bl-sem-bg-canvas)",
          surface: "var(--bl-sem-bg-surface)",
          "surface-raised": "var(--bl-sem-bg-surface-raised)",
          hover: "var(--bl-sem-bg-hover)",
          selected: "var(--bl-sem-bg-selected)",
          "text-primary": "var(--bl-sem-text-primary)",
          "text-secondary": "var(--bl-sem-text-secondary)",
          "text-tertiary": "var(--bl-sem-text-tertiary)",
          border: "var(--bl-sem-border-default)",
          "border-subtle": "var(--bl-sem-border-subtle)",
          "border-faint": "var(--bl-sem-border-faint)",
          "border-strong": "var(--bl-sem-border-strong)",
          accent: "var(--bl-sem-accent)",
          "accent-hover": "var(--bl-sem-accent-hover)",
        },
        status: {
          open: "var(--bl-sem-status-open)",
          "open-bg": "var(--bl-sem-status-open-bg)",
          "open-text": "var(--bl-sem-status-open-text)",
          read: "var(--bl-sem-status-read)",
          "read-bg": "var(--bl-sem-status-read-bg)",
          "read-text": "var(--bl-sem-status-read-text)",
          resolved: "var(--bl-sem-status-done)",
          "resolved-bg": "var(--bl-sem-status-done-bg)",
          "resolved-text": "var(--bl-sem-status-done-text)",
        },
        addressed: {
          DEFAULT: "var(--bl-sem-addressed-bg)",
          border: "var(--bl-sem-addressed-border)",
        },
        accent: {
          DEFAULT: "var(--bl-sem-text-accent)",
          bg: "var(--bl-sem-accent)",
          hover: "var(--bl-sem-accent-hover)",
          "text-hover": "var(--bl-sem-accent-text-hover)",
          ring: "var(--bl-sem-accent-ring)",
          subtle: "var(--bl-sem-accent-subtle)",
        },
        tag: {
          "revision-bg": "var(--bl-sem-tag-revision-bg)",
          "revision-text": "var(--bl-sem-tag-revision-text)",
          "approval-bg": "var(--bl-sem-tag-approval-bg)",
          "approval-text": "var(--bl-sem-tag-approval-text)",
          "blocker-bg": "var(--bl-sem-tag-blocker-bg)",
          "blocker-text": "var(--bl-sem-tag-blocker-text)",
          "question-bg": "var(--bl-sem-tag-question-bg)",
          "question-text": "var(--bl-sem-tag-question-text)",
        },
        ai: {
          bg: "var(--bl-sem-ai-bg)",
        },
        elbow: "var(--bl-sem-elbow)",
        danger: {
          DEFAULT: "var(--bl-sem-danger)",
          bg: "var(--bl-sem-danger-soft-bg)",
          border: "var(--bl-sem-danger-soft-border)",
        },
        warning: {
          DEFAULT: "var(--bl-sem-warning)",
          bg: "var(--bl-sem-warning-soft-bg)",
          border: "var(--bl-sem-warning-soft-border)",
        },
      },
      boxShadow: {
        "sem-none": "var(--bl-sem-shadow-none)",
        "sem-sm": "var(--bl-sem-shadow-sm)",
        "sem-lg": "var(--bl-sem-shadow-lg)",
        "sem-xl": "var(--bl-sem-shadow-xl)",
        "sem-tooltip": "var(--bl-sem-shadow-tooltip)",
        "sem-card": "var(--bl-sem-shadow-card)",
        "sem-halo": "var(--bl-sem-shadow-halo)",
        "sem-halo-error": "var(--bl-sem-shadow-halo-error)",
        "sem-status-open": "var(--bl-sem-shadow-status-open)",
        "sem-status-read": "var(--bl-sem-shadow-status-read)",
        "sem-status-done": "var(--bl-sem-shadow-status-done)",
      },
      fontSize: {},
    },
  },
  plugins: [],
} satisfies Config;
